

analyzers:
  irp6:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Irp6
    analyzers:
      CPU:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Conveyor
        find_and_remove_prefix: Conveyor
        num_items: 3
     

